/** @format */

export const userTableData = [
  {
    id: "S5W4",
    name: { name: "Kristin Watson", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "deanna.curtis@example.com",
    status: "Inactive",
    action: "view",
  },
  {
    id: "F41H",
    name: { name: "Marvin McKinney", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "michelle.rivera@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "GR41",
    name: { name: "Eleanor Pena", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "felicia.reid@example.com",
    status: "Inactive",
    action: "view",
  },
  {
    id: "F41H",
    name: { name: "Marvin McKinney", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "curtis.weaver@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "S5W4",
    name: { name: "Kristin Watson", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "michael.mitc@example.com",
    status: "Inactive",
    action: "view",
  },
  {
    id: "F41H",
    name: { name: "Eleanor Pena", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "willie.jennings@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "GR41",
    name: { name: "Marvin McKinney", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "deanna.curtis@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "B3K7",
    name: { name: "Sarah Johnson", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "sarah.johnson@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "M9R2",
    name: { name: "David Chen", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "david.chen@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "T8L5",
    name: { name: "Emily Rodriguez", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "emily.rodriguez@example.com",
    status: "Inactive",
    action: "view",
  },
  {
    id: "K4P9",
    name: { name: "Michael Brown", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "michael.brown@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "H6D1",
    name: { name: "Jessica Wilson", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "jessica.wilson@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "N2F8",
    name: { name: "Robert Garcia", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "robert.garcia@example.com",
    status: "Inactive",
    action: "view",
  },
  {
    id: "Q7X3",
    name: { name: "Amanda Davis", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "amanda.davis@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "Z1Y4",
    name: { name: "Christopher Lee", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "christopher.lee@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "V5C6",
    name: { name: "Lisa Martinez", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "lisa.martinez@example.com",
    status: "Inactive",
    action: "view",
  },
  {
    id: "U8W0",
    name: { name: "James Taylor", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "james.taylor@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "A3E7",
    name: { name: "Rachel Anderson", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "rachel.anderson@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "L9S2",
    name: { name: "Daniel Thompson", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "daniel.thompson@example.com",
    status: "Inactive",
    action: "view",
  },
  {
    id: "P4J1",
    name: { name: "Nicole White", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "nicole.white@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "R6M5",
    name: { name: "Kevin Harris", avatar: "/profile-img.jpg" },
    userType: "Paid",
    email: "kevin.harris@example.com",
    status: "Active",
    action: "view",
  },
  {
    id: "Y2B8",
    name: { name: "Stephanie Clark", avatar: "/profile-img.jpg" },
    userType: "Free",
    email: "stephanie.clark@example.com",
    status: "Inactive",
    action: "view",
  },
];
